### ISSUE TITLE
Warcraft II

### ISSUE THREAD

**Issue by realnicolbolas** [fonic/wcdctool#2]
Hey hey! I wanted to ask some help on an older game. To give context, the full source code for the PS1 port of warcraft 2 was found online back in june, and i wanted to see if i could attempt to decompile the PC release using the information from that discovery. theres information on how the game was compiled in the leak (it specifies Watcom 3.2 in one of the files) as well as information on how it was compiled like batch files and whatnot. what would i need to have/use to decompile the PC version of the game? as in a step by step (not a very good programmer, just a big war2 fan)

**Comment by fonic** [comment]
I just had a look at the archive. It would seem that this was the original PC version, before it got heavily mutilated for use on PS1 and Sega SATURN. Too bad the original makefiles are no longer there. But it would seem all the original PC version code is still there, have a look at `snd.c` or `gamemap.c` for example (lots of commented out code, lots of comments explaining why something is commented out, replaced etc.).

So... If I would do this, I'd try to reconstruct the PC version from the PS1/SATURN sources archive.

I'm not sure if you understand what decompilation means and/or how it works, no offence. When decompiling software, you try to reconstruct sources from binary data. In the case of Warcraft II, you'd start disassembling the binary (`WAR2.EXE`) and then you'd try to reconstruct sources (i.e. C code) from the disassembly. It's a very lengthy process, especially if you're trying to decompile from binary data to high level language (and that's the case here). Also, if you don't have binaries with debug information, decompilation get's nearly impossible because you just don't have the information you need (like variable/function names or even information about where functions begin/end etc.).

So... are you sure you want to actually _decompile_ the PC version of Warcraft II? Why not reconstruct the PC version sources from the PS1/SATURN port sources? This would be **a lot** easier.

**Comment by realnicolbolas** [comment]
> So... are you sure you want to actually _decompile_ the PC version of Warcraft II? Why not reconstruct the PC version sources from the PS1/SATURN port sources? This would be **a lot** easier.
I can try but i am VERY bad at coding. i have been looking for people to help me out with that but no one so far has been able to. hopefully i can

**Comment by fonic** [comment]
Well, look at it that way: no one (except maybe John Carmack) is born as a good developer. This is a good opportunity to become better and learn. Even more so if you work on something you really like.
